#!/bin/bash
# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
set -Eeuo pipefail && SCRIPTNAME=${0##*/} && die() { [ -z "$*" ] || echo "$SCRIPTNAME: $*" >&2; exit 127 ; }
SCRIPTDIR="${0%/*}"

# Usage: docker_build <Dockerfile> [CacheURL] [ghcrio_user]
DOCKERFILE="$1"
IMAGEURL="${2:-}"
GHCRUSER="${3:-}"
FILEDATE=$(git log -1 --format=%cI -- "$DOCKERFILE" | sed 's/[-T]//g; s/://; s/:.*//')
VERSION="${DOCKERFILE##*Dockerfile.}"-$FILEDATE
PWDHASH=$(pwd | sha256sum | sed 's/\(.\{11\}\).*/\1/')
CITAG=anklang-ci:"$PWDHASH"

if test ! -z "$GHCRUSER" ; then
  cat | docker login ghcr.io -u "$GHCRUSER" --password-stdin
fi

if test -z "$IMAGEURL" ; then
  set -x
  docker build -f $DOCKERFILE -t $CITAG $SCRIPTDIR
else
  DOCKER_IMAGES=$(docker images --format "|{{.ID}}|{{.Repository}}:{{.Tag}}|") # buffer image list to avoid SIGPIPE
  [[ $IMAGEURL =~ ./.*:.* ]] || IMAGEURL="$IMAGEURL:$VERSION"
  CACHE_FROM=
  set -x
  { grep -q "|$IMAGEURL|" <<< "$DOCKER_IMAGES" ||
      docker pull $IMAGEURL ; } &&
    CACHE_FROM=--cache-from=$IMAGEURL
  docker build -f $DOCKERFILE -t $CITAG $SCRIPTDIR $CACHE_FROM
  docker tag $CITAG $IMAGEURL
  docker push $IMAGEURL || true
fi
