# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# == Distribution preparation ==
FROM ubuntu:22.04
ENV DEBIAN_FRONTEND noninteractive

# Use BASH(1) as shell, affects the RUN commands below
RUN ln -sf bash /bin/sh && ls -al /bin/sh

# Upgrade packages, install dependencies, clean up to shrink Docker image
# Add libXss.so, libgtk-3-0 for Electron
RUN apt-get update \
  && apt-get -y upgrade \
  && apt-get install -y \
	     sudo build-essential curl cmake libglib2.0-dev libzstd-dev \
	     build-essential pkg-config git ccache unzip gawk \
	     castxml cppcheck libboost-system-dev \
	     imagemagick librsvg2-bin libxml2-utils libxml2-dev python3 python3-pip \
	     python3-lxml python3-pandocfilters pandoc graphviz universal-ctags \
	     libasound2-dev libflac-dev libopus-dev libjack-dev \
	     libvorbis-dev libmpg123-dev libmp3lame-dev \
	     gettext libgconf-2-4 libgtk2.0-dev libgtk-3-dev squashfs-tools zstd \
	     libgtk-3-0 libxss1 libgbm1 libnss3 \
	     lsb-release wget software-properties-common \
	     xvfb twm ffmpeg doxygen \
  && apt-get clean

# Install recent clang++
RUN \
  --mount=type=cache,target=/var/cache/apt \
  curl -fsSLO https://apt.llvm.org/llvm.sh && chmod +x llvm.sh \
  && yes | ./llvm.sh 18 && rm -f ./llvm.sh \
  && apt-get install -y clang-tidy-18 libclang-18-dev \
  && update-alternatives \
       --install /usr/bin/clang         clang           /usr/bin/clang-18 0 \
       --slave   /usr/bin/clang++       clang++         /usr/bin/clang++-18  \
       --slave   /usr/bin/clang-tidy    clang-tidy      /usr/bin/clang-tidy-18 \
  && apt-get autoremove -y

# Nodejs - https://github.com/nodesource/distributions#nodejs
RUN \
  --mount=type=cache,target=/var/cache/apt \
  mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && rm -f nodesource-repo.gpg.key \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
  && apt-get update \
  && apt-get install -y nodejs \
  && apt-get autoremove -y

# Install TeX and mkdocs for documentation builds
RUN pip install mkdocs-material mkdoxy poxy \
  && apt-get install -y texlive-xetex fonts-sil-charis texlive-binaries texlive-fonts-extra \
  && apt-get clean

# Become non-root, use Github action VM user: uid=1001(runner) gid=127(docker)
RUN groupadd -g 127 docker && useradd -u 1001 -g 127 -m -d /github/home -s /bin/bash runner \
  && echo "runner ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/runner
USER runner

# docker build -t ghcr.io/tim-janik/anklang-ci:jammy-latest -f misc/Dockerfile.jammy misc
# docker run -ti --rm -v $PWD:/hostwd ghcr.io/tim-janik/anklang-ci:jammy-latest
