# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Distribution selection
FROM ubuntu:24.04
ENV DEBIAN_FRONTEND noninteractive

# Use BASH(1) as shell, affects the RUN commands below
RUN ln -sf bash /bin/sh && ls -al /bin/sh

# Upgrade packages, cache /var/cache/apt instead of "apt clean"
RUN \
  --mount=type=cache,target=/var/cache/apt : \
  && apt-get update \
  && apt-get -y upgrade \
  && apt-get autoremove -y

# Add libXss.so, libgtk-3-0 for Electron
RUN \
  --mount=type=cache,target=/var/cache/apt : \
  && apt-get install -y \
	     sudo build-essential curl cmake libglib2.0-dev libzstd-dev \
	     pkg-config git ccache unzip gawk \
	     castxml cppcheck libboost-system-dev \
	     imagemagick librsvg2-bin libxml2-utils libxml2-dev python3 python3-pip \
	     python3-lxml python3-pandocfilters pandoc graphviz universal-ctags \
	     libasound2-dev libflac-dev libopus-dev libjack-dev \
	     libvorbis-dev libmpg123-dev libmp3lame-dev \
	     squashfs-tools zstd gettext \
	     libgtk2.0-dev libgtk-3-dev \
	     libgtk-3-0 libxss1 libgbm1 libnss3 \
	     lsb-release wget software-properties-common \
	     xvfb twm ffmpeg doxygen \
  && apt-get autoremove -y

# Add TeX for PDF rendering
RUN \
  --mount=type=cache,target=/var/cache/apt : \
  && apt-get install -y \
	     texlive-xetex fonts-sil-charis texlive-binaries texlive-fonts-extra \
  && apt-get autoremove -y

# Install recent clang++
RUN \
  --mount=type=cache,target=/var/cache/apt : \
  && curl -fsSLO https://apt.llvm.org/llvm.sh && chmod +x llvm.sh \
  && yes | ./llvm.sh 20 && rm -f ./llvm.sh \
  && apt-get install -y clang-tidy-20 libclang-20-dev \
  && update-alternatives \
       --install /usr/bin/clang         clang           /usr/bin/clang-20 0 \
       --slave   /usr/bin/clang++       clang++         /usr/bin/clang++-20  \
       --slave   /usr/bin/clang-tidy    clang-tidy      /usr/bin/clang-tidy-20 \
  && apt-get autoremove -y

# Nodejs - https://github.com/nodesource/distributions#nodejs
RUN \
  --mount=type=cache,target=/var/cache/apt : \
  && mkdir -p /etc/apt/keyrings \
  && curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg \
  && rm -f nodesource-repo.gpg.key \
  && echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_22.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list \
  && apt-get update \
  && apt-get install -y nodejs \
  && apt-get autoremove -y

# Install mkdocs for documentation builds
ENV PIP_BREAK_SYSTEM_PACKAGES 1
RUN pip install mkdocs-material mkdoxy poxy

# Support `--user runner` for the Github action VM user: uid=1001(runner) gid=127(docker)
RUN : \
  && groupadd -g 127 docker \
  && useradd -u 1001 -g 127 -G 1000 -m -d /github/home -s /bin/bash runner \
  && echo "runner ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/runner

# Become non-root, allow sudo as user
RUN echo "ubuntu ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/ubuntu
USER ubuntu

# docker build -t ghcr.io/tim-janik/anklang-ci:noble-latest -f misc/Dockerfile.noble misc
# docker run -ti --rm -v $PWD:/hostwd -w /hostwd ghcr.io/tim-janik/anklang-ci:noble-latest
