ASE_TEST_LIST := \
  aligned_allocator_tests \
  ase_serialize \
  ase_string_format \
  ase_test_timestamps \
  atomic_bits_test \
  atomic_mpmcstack_test \
  atomic_valuestack_test \
  blake3_tests \
  callback_list_test \
  cotask_int64_result_test \
  cotask_string_result_test \
  cotask_void_test \
  crawler_tests \
  event_list_tests \
  job_queue_tests \
  jsonapi_tests \
  levenshtein_tests \
  loft_allocator_tests \
  loft_shuffle_thread_allocs \
  loft_simple_tests \
  loop_add_timer_test \
  loop_current_multithread_test \
  loop_current_test \
  mathutils_tests \
  member_tmpl_tests \
  memory_cstring_tests \
  mpmc_stack_test \
  nested_cotask_test \
  path_tests \
  promise_already_resolved_test \
  promise_exception_test \
  promise_int64_test \
  promise_multi_waiter_test \
  promise_string_test \
  promise_void_test \
  queuemux_test \
  randomhash_tests \
  regex_tests \
  semaphore_concurrent_test \
  semaphore_multiple_test \
  signalutils_tests \
  sndfile_tests \
  sortnet_tests \
  string_tests \
  test_serializable_hierarchy \
  transport_tests \
  unicode_displayfs_tests \
  unicode_tests \
  utf8_codepoint_bench \
  utf8_strlen_bench_ascii \
  utf8_strlen_bench_high_planes \
  utils_tests \
  zbench_aligned_allocator_aligned_block \
  zbench_aligned_allocator_calloc \
  zbench_aligned_allocator_fast_mem_alloc \
  zbench_aligned_allocator_loft_alloc \
  zbench_aligned_allocator_memalign \
