# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# https://www.mkdocs.org/getting-started/
site_name: Anklang Documentation
site_url: https://tim-janik.github.io/anklang
repo_url: https://github.com/tim-janik/anklang
repo_name: Anklang.git
docs_dir: mkdocs
site_dir: site
copyright: Copyright &copy; 2024 Anklang Project

plugins:
  - search
  - privacy
    # https://squidfunk.github.io/mkdocs-material/plugins/privacy/?h=blank#config.links_attr_map
    # links_attr_map:
    #   target: _blank
  - offline
  - tags

extra_css:
  - style/mkdocs.css
extra_javascript:
  - javascript/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - "About Anklang": index.md
  - "Introductionary Tutorials":
    - "Tutorial 1: Starting to Play Notes": tut-play.md
  - "Howto Guides":
    - "Howto: Setting Up Audio (Linux)": how-audio.md
  - "References":
    - "ANKLANG(1) Manual Page": ch-man-pages.md
    - "User Interface":
      - Clip-List: cliplist.md
      - Piano-Ctrl: piano-ctrl.md
      - Piano-Roll: pianoroll.md
    - JS Scripting: scripting-docs.md
    - "Anklang C++ API":
      - 'C++ Class-Tree':       class-tree.md
      - 'C++ API Links':        AnklangCxx/links.md
      - 'Class List':           AnklangCxx/annotated.md
      - 'Class Members':        AnklangCxx/class_members.md
      - 'Namespace List':       AnklangCxx/namespaces.md
      - 'Namespace Members':    AnklangCxx/namespace_members.md
      - 'Files':                AnklangCxx/files.md
  - "Design & Development":
    - Development Overview: ch-development.md
    - UI Development:
      - Web Components: ch-component.md
      - Component API: jsdocs.md
    - Implementation Details:
      - Making Releases: ch-releasing.md
      - Interpolation Notes: ch-appendix.md

# https://squidfunk.github.io/mkdocs-material/getting-started/
theme:
  name: material
  language: 'en'
  #features:
  #  - navigation.footer
  features:
    - search.suggest
    - search.highlight
    - search.share
    - toc.integrate
    - navigation.tracking
    #- navigation.tabs
    - navigation.sections
    #- navigation.expand
    - navigation.path
  # taken from https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#system-preference
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to system preference
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
extra:
  generator: false
  social:
    - icon: fontawesome/brands/mastodon
      link: https://social.tchncs.de/@timj

# https://squidfunk.github.io/mkdocs-material/setup/extensions/python-markdown-extensions/
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


# docker run --rm -it -v${PWD}:/docs -p 127.0.0.1:8001:8000 ghcr.io/tim-janik/anklang-ci:mkdocs-latest
# docker run --rm -it -v${PWD}:/docs --entrypoint '' squidfunk/mkdocs-material sudo chown 1000:1000 -R /docs/.
