UI_TEST_LIST := \
  clip_test.test_clip_volume \
  clip_test.test_clip_mute \
  clip_test.test_clip_pan \
  clip_test.test_clip_notes \
  clip_test.test_clip_range \
  editable_test.test_editable_initial_value \
  editable_test.test_editable_numeric_value \
  editable_test.test_editable_activate_click \
  editable_test.test_editable_activate_dblclick \
  editable_test.test_editable_enter_commits \
  editable_test.test_editable_escape_cancels \
  editable_test.test_editable_blur_commits \
  editable_test.test_editable_ref_activate \
  project_test.test_project_basic \
  project_test.test_project_master_volume \
  project_test.test_project_track_management \
  project_test.test_project_track_removal_notification \
  track_test.test_track_volume \
  track_test.test_track_pan \
  track_test.test_track_mute \
  track_test.test_track_solo \
  track_test.test_track_midi_channel \
  util_test.test_string_ops \
  util_test.test_number_ops \
  util_test.test_array_ops \
