UI_TEST_LIST := \
  choiceinput_test.test_choiceinput \
  clip_test.test_clip_volume \
  clip_test.test_clip_mute \
  clip_test.test_clip_pan \
  clip_test.test_clip_notes \
  clip_test.test_clip_range \
  contextmenu_test.test_contextmenu \
  devicepanel_test.test_devicepanel \
  editable_test.test_editable \
  knob_test.test_knob \
  numberinput_test.test_numberinput \
  project_test.test_project_basic \
  project_test.test_project_master_volume \
  project_test.test_project_track_management \
  project_test.test_project_track_removal_notification \
  shell_test.test_shell \
  switchinput_test.test_switchinput \
  textinput_test.test_textinput \
  toggle_test.test_toggle \
  track_test.test_track_volume \
  track_test.test_track_pan \
  track_test.test_track_mute \
  track_test.test_track_solo \
  track_test.test_track_midi_channel \
  util_test.test_util \
