# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0
include $(wildcard $>/ui/*.d)

VITE_DEPS :=	# (intermediate) targets required by vite

# This Makefile creates needed inputs unde $>/gen and calls vite
# to bundle assets under $>/ui/.
# * make run - Build UI, start electron app
# * make serve - Run build server for ui/.
# * DevTools can be activated with Shft+Ctrl+I when run from the devleopment tree.

# == gen/aseapi.js ==
ui/aseapi.outdated != test $>/gen/aseapi.js -nt ase/api.hh || echo OUTDATED
# only wait for lib/AnklangSynthEngine if gen/aseapi.js must be re-generated
$>/gen/aseapi.js: jsonipc/jsonipc.js ase/api.hh ui/Makefile.mk $(if $(ui/aseapi.outdated), $(lib/AnklangSynthEngine)) | $>/gen/
	$(QGEN)
	$Q $(CP) $< $@.tmp
	$Q ASAN_OPTIONS=detect_leaks=0 \
	$(lib/AnklangSynthEngine) --norc  -P null -M null --js-api				>> $@.tmp
	$Q echo '/**@type{ServerImpl}*/'							>> $@.tmp
	$Q echo 'export let server = Jsonipc.setup_promise_type (Server, s => server = s);'	>> $@.tmp
	$Q mv $@.tmp $@
VITE_DEPS += $>/gen/aseapi.js

# == ui/assets/AnklangIcons.css ==
$>/gen/assets/AnklangIcons.css: ui/Makefile.mk $(EXTERNAL_BLOBS4ANKLANG_STAMPS)	| $>/gen/assets/
	$(QGEN)
	$Q rm -fr $>/gen/anklangicons/ && tar xf external/blobs4anklang/icons/anklangicons-201123.1.tgz -C $>/gen/
	$Q cd $>/gen/anklangicons/ && $(CP) AnklangIcons.woff2 ../assets/ && $(CP) AnklangIcons.css ../assets/AnklangIcons.css.tmp
	$Q sed -e 's|@font-face *{|@font-face { font-display: block; |' -i $>/gen/assets/AnklangIcons.css.tmp
	$Q rm -r $>/gen/anklangicons/ && mv $@.tmp $@
VITE_DEPS += $>/gen/assets/AnklangIcons.css

# == /gen/assets/fork-awesome.css ==
$>/gen/assets/fork-awesome.css: ui/Makefile.mk			| node_modules/.npm.done $>/gen/assets/
	$(QGEN)
	$Q $(CP) node_modules/fork-awesome/fonts/forkawesome-webfont.woff2 $>/gen/assets/
	$Q sed  -e "/^ *src: *url/s,src: *url(.*);,src: url('forkawesome-webfont.woff2');," \
		-e 's|@font-face *{|@font-face { font-display: block; |' \
		node_modules/fork-awesome/css/fork-awesome.css > $@.tmp
	$Q mv $@.tmp $@
VITE_DEPS += $>/gen/assets/fork-awesome.css

# == /gen/assets/material-icons.css ==
# Providing icon collections via fonts is most resource friendly */
$>/gen/assets/material-icons.css: ui/Makefile.mk			| node_modules/.npm.done $>/gen/assets/
	$(QGEN)
	$Q grep -q '/material-icons.woff2' node_modules/material-icons/iconfont/filled.css || \
		{ echo "$<: failed to find font in node_modules/material-icons/iconfont/" >&2 ; false ; }
	$Q cp node_modules/material-icons/iconfont/material-icons.woff2 $>/gen/assets/material-icons.woff2
	$Q sed -re 's|\boptimizeLegibility\b|optimizelegibility|g' \
		node_modules/material-icons/iconfont/filled.css > $@.tmp
	$Q mv $@.tmp $@
VITE_DEPS += $>/gen/assets/material-icons.css

# == /gen/cursors/cursors.css ==
$>/gen/cursors/cursors.css: $(wildcard ui/cursors/*) Makefile.mk		| $>/gen/cursors/
	$(QECHO) COPY $<
	$Q for SVG in `sed -n "/url.'.gen.cursors\//{ s/.*('.gen.//; s/').*//; p }" ui/cursors/cursors.css` ; do \
		$(CP) ui/"$$SVG" $>/gen/cursors/ || break ; done
	$Q $(CP) ui/cursors/cursors.css $@
VITE_DEPS += $>/gen/cursors/cursors.css

# == /gen/assets/spinner.css ==
# Extract keyframes for rotating spinner.svg into CSS
$>/gen/assets/spinner.css: ui/assets/spinner.svg				| $>/ext/ui/assets/
	$(QGEN)
	$Q sed -rn '/@keyframe/,$${ p; /^\s*}\s*$$/q; }' $< > $@
VITE_DEPS += $>/gen/assets/spinner.css

# == all-components.js ==
$>/gen/all-components.js: ui/Makefile.mk $(wildcard ui/b/*)	| $>/gen/
	$(QGEN)
	$Q echo '/* Generated by: make $@ */'			>  $@.tmp
	$Q for fjs in $$(cd ui/ && echo b/*.js b/*.jsx) ; do			\
		echo "import '../../ui/$$fjs';" ||				\
		exit 1 ; done					>> $@.tmp
	$Q mv $@.tmp $@
VITE_DEPS += $>/gen/all-components.js

# == /gen/assets/ knobs ==
$>/gen/assets/%: $>/images/knobs/%			| $>/gen/assets/
	$(QGEN)
	$Q $(CP) $< $@
VITE_DEPS += $>/gen/assets/cknob193u.png $>/gen/assets/cknob193b.png

# == /gen/assets/ images ==
ui/assets/images := $(wildcard ui/assets/*.svg)
ui/gen/targets   := $(ui/assets/images:ui/%=$>/gen/%)
$(ui/gen/targets): $>/gen/%: ui/%			| $>/gen/assets/
	$(QECHO) COPY $<
	$Q cd ui/ && $(CP) $(<:ui/%=%) --parents $(abspath $>/)/gen/
VITE_DEPS += $(ui/gen/targets)

# == $>/gen/public/anklang.png ==
$>/gen/public/anklang.png: ui/assets/favicon.svg ui/Makefile.mk	| $>/gen/public/
	$(QGEN)
	$Q mkdir -p $>/gen/tmpanklangpng/
	$Q mogrify -density 600 -background transparent -resize 128x128 -format png -path $>/gen/tmpanklangpng/ $<
	$Q cp $>/gen/tmpanklangpng/favicon.png $>/gen/public/favicon.ico
	$Q mv $>/gen/tmpanklangpng/favicon.png $@.tmp && rm -r $>/gen/tmpanklangpng/ && mv $@.tmp $@
VITE_DEPS += $>/gen/public/anklang.png

# == Inter Typeface ==
$>/gen/InterVariable.woff2: $(EXTERNAL_BLOBS4ANKLANG_STAMPS)	| $>/gen/
	$(QGEN)
	$Q $(CP) $< $@
VITE_DEPS += $>/gen/InterVariable.woff2

# == ui/synsmell ==
ui/synsmell.files: $(filter ui/%. ui/b/%, $(LS_TREE_LST)))
$>/.uisynsmell.done: misc/synsmell.ts $(ui/synsmell.files)				| node_modules/.npm.done
	$(QECHO) CHECK 'synsmell (ui/)'
	$Q $(RUNTS) $< --separate-body=0 $(ui/synsmell.files)
	$Q touch $@
$>/.uisynsmell.done: $(if $(filter check,$(MAKECMDGOALS)), FORCE) # force on 'make check'
check: $>/.uisynsmell.done

# == $>/gen/**/*.md - for doc/Makefile.mk ==
# ui/xbcomments.js ui/Makefile.mk node_modules/.npm.done	| $>/gen/b/
$>/gen/%.md: ui/%.js								| $>/gen/b/ node_modules/.npm.done
	$(QGEN)
	$Q node ui/xbcomments.js $< -O $(@D)
VITE_DEPS += $>/doc/anklang-manual.html $>/doc/anklang-internals.html

# == ui dist build ==
VITE_DEPS += $>/version.json
$>/gen/.vite.done: ui/vite.config.ts ui/Makefile.mk $(VITE_DEPS)	| node_modules/.npm.done
	@$(QECHO) BUILD "dist/ (vite build)"
	$Q BUILDDIR='$(abspath $>)' node_modules/.bin/vite -c ui/vite.config.ts build -l warn --emptyOutDir
	$Q ln -fs anklang.png $>/ui/favicon.ico
	$Q gzip -f -9 $>/ui/assets/*.map
	$Q echo '.*/[.].*'		>> $>/ui/.aseignore
	$Q touch $@
ALL_TARGETS += $>/gen/.vite.done

# == serve ==
serve: all
	$Q misc/serve.sh
.PHONY: serve

# == installation ==
ui/installdir ::= $(DESTDIR)$(pkgdir)/ui
ui/install: $>/gen/.vite.done
	@$(QECHO) INSTALL '$(ui/installdir)/'
	$Q rm -f -r '$(ui/installdir)'
	$Q $(INSTALL) -d $(ui/installdir)/ $(ui/installdir)/assets
	$Q $(INSTALL_DATA) -p $>/ui/*.* $(ui/installdir)/
	$Q $(INSTALL_DATA) -p $>/ui/assets/*.* $(ui/installdir)/assets/
	$Q ln -s ../doc $(ui/installdir)/doc
.PHONY: ui/install
install: ui/install
ui/uninstall: FORCE
	@$(QECHO) UNINSTALL '$(ui/installdir)/'
	$Q rm -f -r '$(ui/installdir)'
.PHONY: ui/uninstall
uninstall: ui/uninstall
