# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  push:
    branches: ['main', 'master', 'trunk', 'wip/**']
    tags:     [ 'v[0-9]+.[0-9]+.[0-9]+*' ]
  pull_request:
    branches: ['trunk', 'wip/**']  # Only run PRs targeting these branches

jobs:

  ReleaseArtifacts:
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:ci-latest', options: --user runner }
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags  # Fix actions/checkout#290
    - run: |
        make -w dist
        mkdir /tmp/anklang && tar xf artifacts/anklang-*.tar.zst -C /tmp/anklang --strip-components=1
        cd /tmp/anklang
        echo -e ' prefix=/tmp/inst\n CC=clang \n CXX=clang++ \n INSN=fma ' > config-defaults.mk
    - uses: actions/upload-artifact@v4
      with: { name: AnklangTarball, path: artifacts/ }
    - working-directory: /tmp/anklang
      run: |
        make -w all -j`nproc`
    - working-directory: /tmp/anklang
      run: |
        make -w strict -j`nproc`
    - working-directory: /tmp/anklang
      run: |
        make -w install
    - working-directory: /tmp/anklang
      run: |
        make -w installcheck -j`nproc`
    - working-directory: /tmp/anklang
      run: |
        make -w uninstall
    - working-directory: /tmp/anklang
      run: |
        misc/mkdeb.sh
    - working-directory: /tmp/anklang
      run: |
        misc/mkAppImage.sh
    - uses: actions/upload-artifact@v4
      with: { name: AnklangBinaries, path: /tmp/anklang/artifacts/ }

  NobleClangTidy:
    if: ${{ ! contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:ci-latest', options: --user runner }
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags  # Fix actions/checkout#290
    - run: git describe --always --long
    - name: 'Configure build presets'
      run: |
        echo -e ' prefix=/\n CC=clang \n CXX=clang++ \n CLANG_TIDY=clang-tidy ' > config-defaults.mk
    - run: |
        make -j`nproc` all
    - run: |
        make -j`nproc` check
    - name: 'Make clang-tidy'
      run: |
        make -j`nproc` clang-tidy
    # Artifact upload from clang-tidy
    - uses: actions/upload-artifact@v4
      with: { name: clang-tidy, path: out/clang-tidy/ }
    #- name: 'Make branch-check'
    #  # Use non-0 exit status for a failing branch-check on PRs
    #  run: |
    #    test -z "${{ github.event.pull_request }}" || BRANCH_CHECK_EXIT=77
    #    make branch-check BRANCH_CHECK_EXIT=$BRANCH_CHECK_EXIT
    #^^^ NOte, `make branch-check` does another clang-tidy run

  #ArchReplay:
  #  runs-on: ubuntu-latest
  #  container: { image: 'ghcr.io/tim-janik/anklang-ci:arch-latest' }
  #  steps:
  #  - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
  #  - run: git fetch -f --tags # Fix actions/checkout#290
  #  - run: git describe --always --long
  #  - name: 'Configure build presets'
  #    run: |
  #      echo 'prefix=/' > config-defaults.mk   ;# reset any previous config-defaults.mk
  #  - name: 'Build Anklang'
  #    run: |
  #      make GCC_COLORS="" -j`nproc` all
  #  - name: 'Run Tests'
  #    run: |
  #      make -j`nproc` check
  #  - name: 'Run X11 GUI Tests'
  #    run: |
  #      make x11test-v
  #  # Artifact upload from x11test
  #  - uses: actions/upload-artifact@v4
  #    if: ${{ always() }}
  #    with: { name: "x11test", path: "out/x11test/" }

  CreateRelease:
    runs-on: ubuntu-latest
    needs: [ ReleaseArtifacts ]
    if: github.ref_type == 'tag'        # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
    # https://docs.github.com/en/actions/security-for-github-actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions: { contents: write }    # allow github.token to create a release
    env: { GH_TOKEN: "${{ github.token }}" }
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags  # Fix actions/checkout#290
    - uses: actions/download-artifact@v4
      with: { path: ./artifacts, merge-multiple: true }
    - run: ls -alR artifacts/
    - run: |
        .github/workflows/gh-release.sh "Anklang"

  Ping-IRC:
    # Always run, announce tag and trunk pushes only
    if: ${{ always() && github.event_name == 'push' && (github.ref == 'refs/heads/trunk' || github.ref_type == 'tag') }}
    runs-on: ubuntu-latest
    needs: [ ReleaseArtifacts, CreateRelease, NobleClangTidy ]
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags  # Fix actions/checkout#290
    - name: Ping-IRC
      if: ${{ always() && !env.ACT }}  # IRCBOT_JOBS indicates 'success'
      env: { IRCBOT_JOBS: "${{ join(needs.*.result, ' ') }}" }
      run: .github/workflows/ircbot.py -q -j "#Anklang" -G
