# This Source Code Form is licensed MPL-2.0: http://mozilla.org/MPL/2.0

# Linting: xclip -sel c <.github/workflows/testing.yml # https://rhysd.github.io/actionlint/

on:
  pull_request:
  push:
    branches: [ '**' ]
    # tags:   [ 'v[0-9]+.[0-9]+.[0-9]+*' ]

jobs:

  ReleaseArtifacts:
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:ci-latest', options: --user runner }
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags	# Fix actions/checkout#290
    - run: |
        make -w dist
        mkdir /tmp/anklang && tar xf artifacts/anklang-*.tar.zst -C /tmp/anklang --strip-components=1
        cd /tmp/anklang
        echo -e ' prefix=/tmp/inst\n CC=clang \n CXX=clang++ \n INSN=fma ' > config-defaults.mk
    - uses: actions/upload-artifact@v4
      with: { name: AnklangTarball, path: artifacts/ }
    - working-directory: /tmp/anklang
      run: |
        make -w all -j`nproc`
    - working-directory: /tmp/anklang
      run: |
        make -w check -j`nproc`
    - working-directory: /tmp/anklang
      run: |
        make -w install
    - working-directory: /tmp/anklang
      run: |
        make -w installcheck -j`nproc`
    - working-directory: /tmp/anklang
      run: |
        make -w uninstall
    - working-directory: /tmp/anklang
      run: |
        misc/mkdeb.sh
    - working-directory: /tmp/anklang
      run: |
        misc/mkAppImage.sh
    - uses: actions/upload-artifact@v4
      with: { name: AnklangBinaries, path: /tmp/anklang/artifacts/ }

  NobleClangTidy:
    if: ${{ ! contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    container: { image: 'ghcr.io/tim-janik/anklang-ci:ci-latest', options: --user runner }
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags	# Fix actions/checkout#290
    - run: git describe --always --long
    - name: 'Configure build presets'
      run: |
        echo -e ' prefix=/\n CC=clang \n CXX=clang++ \n CLANG_TIDY=clang-tidy ' > config-defaults.mk
    - run: |
        make -j`nproc` all
    - run: |
        make -j`nproc` check
    - name: 'Make clang-tidy'
      run: |
        make -j`nproc` clang-tidy
    # Artifact upload from clang-tidy
    - uses: actions/upload-artifact@v4
      with: { name: clang-tidy, path: out/clang-tidy/ }
    - name: 'Make branch-check'
      # Use non-0 exit status for a failing branch-check on PRs
      run: |
        test -z "${{ github.event.pull_request }}" || BRANCH_CHECK_EXIT=77
        make branch-check BRANCH_CHECK_EXIT=$BRANCH_CHECK_EXIT

  #ArchReplay:
  #  runs-on: ubuntu-latest
  #  container: { image: 'ghcr.io/tim-janik/anklang-ci:arch-latest' }
  #  steps:
  #  - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
  #  - run: git fetch -f --tags	# Fix actions/checkout#290
  #  - run: git describe --always --long
  #  - name: 'Configure build presets'
  #    run: |
  #      echo 'prefix=/' > config-defaults.mk	;# reset any previous config-defaults.mk
  #  - name: 'Build Anklang'
  #    run: |
  #      make GCC_COLORS="" -j`nproc` all
  #  - name: 'Run Tests'
  #    run: |
  #      make -j`nproc` check
  #  - name: 'Run X11 GUI Tests'
  #    run: |
  #      make x11test-v
  #  # Artifact upload from x11test
  #  - uses: actions/upload-artifact@v4
  #    if: ${{ always() }}
  #    with: { name: "x11test", path: "out/x11test/" }

  Ping-IRC:
    if: always()
    needs: [ ReleaseArtifacts, NobleClangTidy ]
    runs-on: ubuntu-latest
    steps:
    - { uses: actions/checkout@v4, with: { fetch-depth: 0 } }
    - run: git fetch -f --tags	# Fix actions/checkout#290
    - name: Check-Jobs
      run: |
        echo '${{ needs.ReleaseArtifacts.result }}' '${{ needs.NobleClangTidy.result }}'
        [[ ${{ needs.ReleaseArtifacts.result }}    =~ success|skipped ]]
        [[ ${{ needs.NobleClangTidy.result }} =~ success|skipped ]]
    - name: Ping-IRC
      if: ${{ always() && !env.ACT }}
      run: |
        .github/workflows/ircbot.py -q -j "#Anklang" -G -S '${{ job.status }}' "$(git log -1 --format=%s)"
